name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Spacy Model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run vulnerability scan
      run: |
        python test2.py

    - name: Upload vulnerability report
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-report
        path: vulnerability_report.txt
