name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Recreate token.pickle
      run: |
        echo "${{ secrets.GMAIL_OAUTH_TOKEN }}" | base64 --decode > token.pickle
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt

    - name: Run tests and email report
      run: |
        python test2.py
      # env:
      #   CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #   CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #   REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      #   GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      #   GMAIL_USER_ID: ${{ secrets.GMAIL_USER_ID }}
